@startuml ER Diagram

' ER diagram with only 1:1 and 1:N relationships.
hide circle
skinparam linetype ortho

' Entities
entity "Student" as Student {
    *id: integer <<generated>>
    --
    *first_name: text
    *last_name: text
    *date_of_birth: date
    *email: text <<unique>>
    *created_at: timestamp
    *updated_at: timestamp
}

entity "Address" as Address {
    *id: integer <<generated>>
    --
    *street: text
    *city: text
    *zip_code: text
}

entity "Book" as Book {
    *id: integer <<generated>>
    --
    *name: text
    *description: text
    *type: BookType
    *genre: JSON
    *published_at: date
    *author: text
    *isbn: text <<unique>>
    *rented: boolean
    * **student_id**: integer <<FK>>
}

' Relationships
Student ||--|| Address : "has"
Student ||--o{ Book : "rents"


footer Ole Menke | Paul Bräuninger

@enduml
